/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Hooks.h                                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ncotte <marvin@42lausanne.ch>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/02/10 13:56:05 by ncotte            #+#    #+#             */
/*   Updated: 2023/02/10 13:56:06 by ncotte           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef HOOKS_H
# define HOOKS_H

/// @brief Hooks
enum {
	ON_KEYDOWN = 2,
	ON_KEYUP = 3,
	ON_MOUSEDOWN = 4,
	ON_MOUSEUP = 5,
	ON_MOUSEMOVE = 6,
	ON_EXPOSE = 12,
	ON_DESTROY = 17
};

/// @brief Mouse buttons
enum {
	LEFT_CLICK = 1,
	RIGHT_CLICK = 2,
	MIDDLE_CLICK = 3,
	SCROLL_UP = 4,
	SCROLL_DOWN = 5
};

/// @brief Keyboard buttons
enum {
	KEY_A,
	KEY_S,
	KEY_D,
	KEY_F,
	KEY_H,
	KEY_G,
	KEY_Z,
	KEY_X,
	KEY_C,
	KEY_V,
	UNKNOWN_10_,
	KEY_B,
	KEY_Q,
	KEY_W,
	KEY_E,
	KEY_R,
	KEY_Y,
	KEY_T,
	KEY_1,
	KEY_2,
	KEY_3,
	KEY_4,
	KEY_6,
	KEY_5,
	KEY_EQUAL,
	KEY_9,
	KEY_7,
	KEY_MINUS,
	KEY_8,
	KEY_0,
	KEY_CLOSE_SQUARE_BRACKET,
	KEY_O,
	KEY_U,
	KEY_OPEN_SQUARE_BRACKET,
	KEY_I,
	KEY_P,
	KEY_RETURN,
	KEY_L,
	KEY_J,
	KEY_APOSTROPHE,
	KEY_K,
	KEY_SEMICOLON,
	KEY_BACKSLASH,
	KEY_COMMA,
	KEY_SLASH,
	KEY_N,
	KEY_M,
	KEY_PERIOD,
	KEY_TAB,
	KEY_SPACE,
	KEY_BACKTICK,
	KEY_DELETE,
	UNKNOWN_52_,
	KEY_ESC,
	UNKNOWN_54_,
	KEY_CMD,
	UNKNOWN_56_,
	KEY_LEFT_SHIFT,
	KEY_LEFT_ALT,
	KEY_LEFT_CTRL,
	KEY_RIGHT_SHIFT,
	KEY_RIGHT_ALT,
	KEY_RIGHT_CTRL,
	KEY_FN,
	KEY_F17,
	NUMPAD_DOT,
	UNKNOWN_66_,
	NUMPAD_ASTERISK,
	UNKNOWN_68_,
	NUMPAD_PLUS,
	UNKNOWN_70_,
	NUMPAD_CLEAR,
	UNKNOWN_72_,
	UNKNOWN_73_,
	UNKNOWN_74_,
	NUMPAD_SLASH,
	NUMPAD_ENTER,
	UNKNOWN_77_,
	NUMPAD_MINUS,
	KEY_F18,
	KEY_F19,
	NUMPAD_EQUAL,
	NUMPAD_0,
	NUMPAD_1,
	NUMPAD_2,
	NUMPAD_3,
	NUMPAD_4,
	NUMPAD_5,
	NUMPAD_6,
	NUMPAD_7,
	KEY_F20,
	NUMPAD_8,
	NUMPAD_9,
	UNKNOWN_93_,
	UNKNOWN_94_,
	UNKNOWN_95_,
	KEY_F5,
	KEY_F6,
	KEY_F7,
	KEY_F3,
	KEY_F8,
	KEY_F9,
	UNKNOWN_102_,
	KEY_F11,
	UNKNOWN_104_,
	KEY_F13,
	KEY_F16,
	KEY_F14,
	UNKNOWN_108_,
	KEY_F10,
	UNKNOWN_110_,
	KEY_F12,
	UNKNOWN_112_,
	KEY_F15,
	UNKNOWN_114_,
	KEY_HOME,
	KEY_PAGE_UP,
	UNKNOWN_117_,
	KEY_F4,
	KEY_END,
	KEY_F2,
	KEY_PAGE_DOWN,
	KEY_F1,
	KEY_LEFT,
	KEY_RIGHT,
	KEY_DOWN,
	KEY_UP,
	UNKNOWN_127_,
};

#endif
